baseURL: https://riaxiii.github.io/blog/
languageCode: en-us
title: Ria
theme: ["hugo-PaperMod"]
pagination:
  pagerSize: 5
params:
  description: "Nonbiri"
  homeInfoParams:
    Title: "^._.^"
    Content: "⚠️caution: casual blogging, translated content with 0% accuracy, non-profit⚠️"
languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Tags
          url: tags
          weight: 10
