baseURL: https://riaxiii.github.io/blog/
languageCode: en-us
title: Ria
theme: ["hugo-PaperMod"]
pagination:
  pagerSize: 5
params:
  description: "Archive เรื่อยเปื่อย"
  homeInfoParams:
    Title: "^._.^"
    Content: "⚠️คำเตือน⚠️ Blog นี้ส่งมอบอะไรเรื่อยเปื่อย และการแปลมั่ว ๆ แบบไม่รับประกันความถูกต้อง สามารถรับชมได้ทุกเพศทุกวัย, non-profit"
  socialIcons:
    - name: "Twitter"
      url: "https://twitter.com/riaxiii"
languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Tags
          url: tags
          weight: 10
